version: '3.7'
services:
  backend:
    image: avikast-mediasoup
    build: .
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 3080:3080
      - 3443:3443
    environment:
      NODE_ENV: testing
volumes:
  db:
networks:
  backend:
